/** §7 — Order status state machine values */
export enum OrderStatus {
  PENDING = 'PENDING',
  REJECTED = 'REJECTED',
  AWAITING_BUYER_PICKUP = 'AWAITING_BUYER_PICKUP',
  AWAITING_DELIVERER_ASSIGN = 'AWAITING_DELIVERER_ASSIGN',
  AWAITING_DELIVERER_PICKUP = 'AWAITING_DELIVERER_PICKUP',
  IN_TRANSIT = 'IN_TRANSIT',
  COMPLETED = 'COMPLETED',
}
